CREATE TABLE bookmarks(id SERIAL PRIMARY KEY, url VARCHAR(60));
CREATE TABLE comments(id SERIAL PRIMARY KEY, text VARCHAR(240), bookmark_id INTEGER, FOREIGN KEY(bookmark_id) REFERENCES bookmarks (id));
CREATE TABLE tags(id SERIAL PRIMARY KEY, content VARCHAR(60));
CREATE TABLE bookmark_tags(id SERIAL PRIMARY KEY, bookmark_id INTEGER REFERENCES bookmarks (id), tag_id INTEGER REFERENCES tags (id));
CREATE TABLE users(id SERIAL PRIMARY KEY, email VARCHAR(60), password VARCHAR(140));
